version: 0.0
os: linux
files:
  - source: previous_image_tag.txt
    destination: /home/ec2-user/codeDeploy/  
hooks:
  AfterInstall:
    - location: scripts/health_check.sh
      timeout: 300
      runas: root
      onFailure: CONTINUE
    - location: scripts/rollback.sh
      timeout: 300
      runas: root
      