version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/stop-containers.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy-stack.sh
      timeout: 300
      runas: root
