services:
  application-services-1:
    image: 637423298319.dkr.ecr.us-west-2.amazonaws.com/manu/worker-services:latest
    hostname: worker-services-1.manuplex-uswest-2.local
    networks:
      - MP-prod-net1-overlay
    volumes:
      - ./certs:/tls
      - worker-services-logs:/var/log/worker-services-1 # Named volume for logs
    environment:
      - LOG_LEVEL=debug
      - ENV=prod
      - WS_WORKER_COUNT=${WS_WORKER_COUNT:-4}
      - TEMPORAL_NAMESPACE=ob1-temporal-namespace
      - TEMPORAL_ADDRESS=temporal-server-1.manuplex-uswest-2.local:7233
      - AG_TEMPORAL_TASK_QUE_NAME=agentprocess_QUEUE
      - REDIS_STACK_HOST=redis-stack-server-1.manuplex-uswest-2.local
      - REDIS_STACK_PORT=6379
      - WS_WORKER_COUNT=2
      - WS_HEALTHCHECK_INTERVAL=30000
      - WS_HEALTHCHECK_TIMEOUT=2000
      - WS_WAIT_SHUTDOWN_TIME=15000
      - WS_MAX_SHUTDOWN_ATTEMPTS=3
      - WS_MAX_HEALTHCHECK_MISSED=9
      - WS_MAX_EXECUTION_TIME=900000
      - RESTART_DELAY=1000
    secrets:
      - WORKER_SERVICES_REDIS_STACK_PASSWORD
    command: >
      sh -c "
      export REDIS_STACK_PASSWORD=$$(cat /run/secrets/WORKER_SERVICES_REDIS_STACK_PASSWORD | tr -d '\\n') &&
      node --trace-warnings dist/main.js"
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "3"
    deploy:
      placement:
        constraints:
          - "node.hostname == MP1-prod0"

networks:
  MP-dev-net1-overlay:
    external: true
  MP-prod-net1-overlay:
    external: true

volumes:
  worker-services-logs:
    driver: local

secrets:
  WORKER_SERVICES_REDIS_STACK_PASSWORD:
    external: true
  



  

