services:
  worker-services-1:
    build: ./worker-services-1
    container_name: worker-services-1
    hostname: worker-services-1.manuplex-uswest-2.local
    networks:
      - ${NETWORK_NAME}
    env_file:
      - .env
    volumes:
      - ./certs:/tls
      - worker-services-logs:/var/log/worker-services-1 # Named volume for logs
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-log}
      - ENV=${ENV:-dev}
      - WS_WORKER_COUNT=${WS_WORKER_COUNT:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1g # Memory limit of 1GB
          cpus: "1.0" # Restrict to 1 CPU
        reservations:
          memory: 512m # Reserve 512MB of memory

volumes:
  worker-services-logs:
    driver: local

networks:
  MP-local-net1-overlay:
    external: true
  MP-dev-net1-overlay:
    external: true
  MP-prod-net1-overlay:
    external: true
